### ISSUE TITLE
ODBP: Minimale landingspagina

### ISSUE THREAD

**Issue by felixcicatt** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Burger-Portaal#19]

**Comment by felixcicatt** [comment]
@MarcoKlerks ik heb deze vast aangemaakt, kan jij verder aanvullen?

**Comment by MarcoKlerks** [comment]
@felixcicatt Duplicaat van / alternatief voor #17. Ik wil geen landingspagina, maar een redirect. Ik zal deze story van de backlog halen.
