### ISSUE TITLE
ODBP: gepubliceerde documenten downloadbaar maken vanaf ODBP

### ISSUE THREAD

**Issue by felixcicatt** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Burger-Portaal#20]
In het ODBP willen we de bestanden bij gepubliceerde documenten uit de ODRC publiek ontsluiten, zodat deze een link kunnen krijgen in de WOO-sitemap.

**Acceptatiecriteria**
- De bestanden bij gepubliceerde documenten zijn beschikbaar in het ODBP, op hetzelfde pad als in de ODRC (`/api/{versie}/documenten/{id}/download`)
- De bestanden bij niet-gepubliceerde documenten zijn **niet** beschikbaar in het ODBP

**Comment by MarcoKlerks** [comment]
@felixcicatt Hoe wordt de URL in het ODBP samengesteld? Als ik dat weet, dan kan ik mogelijk ook testen.

Ik kan ook wachten tot de sitemap online is, zodat ik daaruit de URL ven aan document kan halen.

**Comment by felixcicatt** [comment]
@MarcoKlerks hetzelfde als in ODPC / de api van ODRC: `/api/{versie}/documenten/{id}/download`. Het makkelijkst is denk ik om vanuit ODPC rechtermuisklik te doen op de downloadlink, deze te kopieren in de browser en `odpc` in de url vervangen door `odbp`: 
![image](https://github.com/user-attachments/assets/d6819f27-45b8-416b-9136-c44583ca47b7)
